######################################################################
# Automatically generated by qmake (2.01a) mar 10. gio 01:03:47 2008
######################################################################
QT += core gui widgets

TEMPLATE = app
TARGET = QUnitMargin

CONFIG   +=  QT

DEPENDPATH += .
INCLUDEPATH += .



HEADERS += QUnitMargin.h 

SOURCES += main.cpp \
           QUnitMargin.cpp
